// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchPack(arg1:string,arg2:Array<string>):Promise<any>;

export function Disassemble(arg1:string):Promise<any>;

export function FileList(arg1:string):Promise<any>;

export function GetApkInfo(arg1:string):Promise<any>;

export function OpenFile():Promise<any>;
