// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AndroidManifestInfo(arg1) {
  return window['go']['project']['Project']['AndroidManifestInfo'](arg1);
}

export function BatchPack(arg1, arg2, arg3) {
  return window['go']['project']['Project']['BatchPack'](arg1, arg2, arg3);
}

export function BatchPermissionPack(arg1, arg2, arg3) {
  return window['go']['project']['Project']['BatchPermissionPack'](arg1, arg2, arg3);
}

export function CloseApp(arg1) {
  return window['go']['project']['Project']['CloseApp'](arg1);
}

export function Disassemble(arg1) {
  return window['go']['project']['Project']['Disassemble'](arg1);
}

export function FileList(arg1) {
  return window['go']['project']['Project']['FileList'](arg1);
}

export function GetApkInfo(arg1) {
  return window['go']['project']['Project']['GetApkInfo'](arg1);
}

export function OpenFile() {
  return window['go']['project']['Project']['OpenFile']();
}

export function OpenOutput() {
  return window['go']['project']['Project']['OpenOutput']();
}
