// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIps():Promise<any>;

export function GetStatus(arg1:number):Promise<any>;

export function StartServer(arg1:number):Promise<any>;

export function StopServer():Promise<any>;
