// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIps() {
  return window['go']['upload']['Web']['GetIps']();
}

export function GetStatus(arg1) {
  return window['go']['upload']['Web']['GetStatus'](arg1);
}

export function StartServer(arg1) {
  return window['go']['upload']['Web']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['upload']['Web']['StopServer']();
}
